// swift-tools-version: 5.9
//
// Generated by elo-ios-sdk-source/scripts/build-xcframework.sh during
// release publishing. Do not edit manually; rerun the iOS SDK publish
// workflow to regenerate.

import PackageDescription

let package = Package(
    name: "EloAds",
    platforms: [
        .iOS(.v16),
    ],
    products: [
        .library(name: "EloAds", targets: ["EloAds"]),
        .library(
            name: "EloAdsMediationAdMob",
            targets: ["EloAdsMediationAdMob", "EloAdsMediationAdMobDependencies"]
        ),
    ],
    dependencies: [
        .package(
            url: "https://github.com/googleads/swift-package-manager-google-mobile-ads.git",
            from: "13.3.0"
        ),
    ],
    targets: [
        .binaryTarget(
            name: "EloAds",
            url: "https://github.com/growlads/elo-ios-sdk/releases/download/0.1.5/EloAds.xcframework.zip",
            checksum: "f66f6e3b3d1fa85660423b02436ab0dc74ad1c7c32f54fc76a67f6dea2d40d4b"
        ),
        .binaryTarget(
            name: "EloAdsMediationAdMob",
            url: "https://github.com/growlads/elo-ios-sdk/releases/download/0.1.5/EloAdsMediationAdMob.xcframework.zip",
            checksum: "dd1b5ba81a79167afe544a267c93c6758115ac31b49fba6e147026d28c0efa64"
        ),
        .target(
            name: "EloAdsMediationAdMobDependencies",
            dependencies: [
                "EloAds",
                "EloAdsMediationAdMob",
                .product(
                    name: "GoogleMobileAds",
                    package: "swift-package-manager-google-mobile-ads"
                ),
            ],
            path: "Sources/EloAdsMediationAdMobDependencies"
        ),
    ]
)
