// swift-tools-version: 5.9
//
// Generated by EloIosSdk/scripts/build-xcframework.sh during release
// publishing. Do not edit manually; rerun the iOS SDK publish workflow to
// regenerate.

import PackageDescription

let package = Package(
    name: "EloAds",
    platforms: [
        .iOS(.v16),
    ],
    products: [
        // The SDK. `import EloAds` is everything.
        .library(name: "EloAds", targets: ["EloAds"]),
    ],
    targets: [
        .binaryTarget(
            name: "EloAds",
            url: "https://github.com/growlads/elo-ios-sdk/releases/download/0.0.1/EloAds.xcframework.zip",
            checksum: "18bc8eb588b3e03aafc980ceaa84215620384f2c5e20b66630176018fd643edb"
        ),
    ]
)
