// swift-tools-version: 5.9
//
// Generated by elo-sdk-source/ios/scripts/build-xcframework.sh during
// release publishing. Do not edit manually; rerun the iOS SDK publish
// workflow to regenerate.

import PackageDescription

let package = Package(
    name: "EloAds",
    platforms: [
        .iOS(.v16),
    ],
    products: [
        .library(name: "EloAds", targets: ["EloAds"]),
        .library(
            name: "EloAdsMediationAdMob",
            targets: ["EloAdsMediationAdMob", "EloAdsMediationAdMobDependencies"]
        ),
    ],
    dependencies: [
        .package(
            url: "https://github.com/googleads/swift-package-manager-google-mobile-ads.git",
            from: "13.3.0"
        ),
    ],
    targets: [
        .binaryTarget(
            name: "EloAds",
            url: "https://github.com/growlads/elo-ios-sdk/releases/download/0.1.8/EloAds.xcframework.zip",
            checksum: "f041152b37822fae521d8e7d2ff97965ed19eb70e3f5b5015195fa321e2cf5e6"
        ),
        .binaryTarget(
            name: "EloAdsMediationAdMob",
            url: "https://github.com/growlads/elo-ios-sdk/releases/download/0.1.8/EloAdsMediationAdMob.xcframework.zip",
            checksum: "580e85a64ef2a774e709c9be5bfbd1fb884f85b001830592c2f0d8bd6ac2f74e"
        ),
        .target(
            name: "EloAdsMediationAdMobDependencies",
            dependencies: [
                "EloAds",
                "EloAdsMediationAdMob",
                .product(
                    name: "GoogleMobileAds",
                    package: "swift-package-manager-google-mobile-ads"
                ),
            ],
            path: "Sources/EloAdsMediationAdMobDependencies"
        ),
    ]
)
