name: Integration question
description: Help with integrating the SDK into your app.
labels: ["question"]
body:
  - type: input
    id: sdk_version
    attributes:
      label: SDK version
      placeholder: "0.0.7"
  - type: textarea
    id: goal
    attributes:
      label: What are you trying to do?
    validations:
      required: true
  - type: textarea
    id: tried
    attributes:
      label: What have you tried?
      description: Code snippets, links to your repo, etc.
